name: LittleBrother
version: 1.0
author: Pyramid
main: com.Pyramid.LittleBrother.LittleBrother
commands:
   basic:
      description: Commands of LittleBrother.
      usage: /lb
      permission: LittleBrother.lb
      permission-message: You don't have <permission>
