name: LittleBrother
version: 1.0-alpha
author: Pyramid
main: com.Pyramid.LittleBrother.LittleBrother
commands:
   LittleBrother:
      description: LittleBrother的指令.
      usage: /LittleBrother 获得更多帮助
      aliases: [lb]
      permission: LittleBrother.lb
      permission-message: 你没有 <permission> 的权限
